# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: ReadMe
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/github-metrics.svg
          # Options
          user: kom0055
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 100000
          repositories_forks: no
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: User, login
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'Generate Contribution Snake'
