# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: ReadMe
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/github-metrics.svg
          # Options
          user: kom0055
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 100000
          repositories_forks: no
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: User, login